
version: 0.2
phases:
  install:
    commands:
      - ls
      - pwd
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket builds123 --output-template-file NewSamTemplate.yaml
artifacts:
  type: zip
  files:
    - NewSamTemplate.yaml
