AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Autodeply Test for Chuck-E
Globals:
  Function:
    Runtime: python3.6
    Timeout: 180
Resources:
    wotdGrabber:
        Type: AWS::Serverless::Function
        Properties:
            Role: arn:aws:iam::907740290096:role/service-role/Admin
            Handler: wotd-grabber.lambda_handler
            CodeUri: ./wotd-grabber/wotd-grabber/
            Events:
                 Type: Schedule
                 Properties:
                    Schedule: cron(0 7 * * ? *)

    wotdSkill:
        Type: AWS::Serverless::Function
        Properties:
            Role: arn:aws:iam::907740290096:role/service-role/Admin
            Handler: wotd_skill.lambda_handler
            CodeUri: ./wotd-skill/wotd_skill.py
            Events:
                AlexaSkillEvent:
                    Type:AlexaSkill

    wotdTestTable:
        Type: AWS::Serverless::SimpleTable
        Properties:
            PrimaryKey:
                Name: word
                Type: String
            ProvisionedThroughput:
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5
